package com.kaavalan.note.data.vault

/**
 * Tier 1.1 (v2.0): clean error surface for the .baton-vault file
 * format. Sealed class so the Compose dialog can `when`-match and
 * surface the right string. The importer does NOT distinguish
 * "wrong passphrase" from "tampered header" / "tampered payload"
 * to avoid giving an attacker an oracle — both surfaces
 * `IncorrectPassphrase`.
 */
sealed class VaultError(message: String) : Exception(message) {

    /** The file is not a Baton vault (bad magic, truncated, etc.). */
    class NotAVault(reason: String) : VaultError(reason)

    /** The file's version byte is higher than this app supports. */
    class UnsupportedVersion(version: Int) :
        VaultError("Unsupported vault version: $version")

    /** The file's kdf_id is not implemented in this app. */
    class UnsupportedKdf(kdfId: Int) :
        VaultError("Unsupported KDF: $kdfId")

    /**
     * The passphrase is wrong, OR the file is corrupt, OR the file
     * was tampered with. We do NOT distinguish these three to
     * avoid giving an attacker an oracle. Maps to the user string
     * "Incorrect passphrase".
     */
    class IncorrectPassphrase : VaultError("Incorrect passphrase")

    /** I/O error reading or writing. */
    class IoError(reason: String) : VaultError(reason)

    /** Disk full writing the imported DB. */
    class DiskFull : VaultError("Not enough space to save the vault")

    /**
     * v1.8.0 (PROD-READINESS-P2-#1): the multi-user
     * key-share unwrap failed. Three failure modes:
     *  (a) wrong passphrase for the user (the most
     *      common case — the user mistyped)
     *  (b) share version is not supported by this build
     *      (the share was generated by a newer app
     *      and the user hasn't upgraded)
     *  (c) share is corrupt (the persisted bytes were
     *      truncated, e.g. a half-written WAL row)
     *
     *  We do NOT distinguish (a) from (c) to avoid
     *  giving an attacker an oracle. (b) is safe to
     *  surface because the version byte is
     *  unauthenticated.
     */
    class MasterKeyUnwrap(reason: String) : VaultError(reason)
}
