package com.kaavalan.note.ui.util

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Build
import com.kaavalan.note.R
import com.kaavalan.note.ui.settings.AppVersion
import java.net.URLEncoder

/**
 * v1.9.9 (A10 audit fix): one-tap "report a problem" helper.
 *
 * The Settings sheet has three ways to contact support, each
 * serving a distinct purpose:
 *
 *  1. **Support** (always visible, `mailto:`, body = version +
 *     device) — for general questions. The user writes their
 *     own description in the email composer.
 *  2. **Report a problem** (this helper, always visible,
 *     `mailto:`, body = version + device + inline crash log if
 *     one exists) — for bug reports. One tap goes straight to
 *     the email composer with the most recent crash log
 *     prepended to the body so the support reply can diagnose
 *     the issue without a back-and-forth.
 *  3. **Share crash log** (visible only when a crash log
 *     exists, system share sheet, file attached) — for users
 *     who want to share the crash log via a non-email app
 *     (Telegram, Drive, Notes, etc.).
 *
 * The `mailto:` path is one tap deep. The share-sheet path is
 * two taps (tap the row, then pick an app from the chooser).
 * For a bug report, one tap is materially better — every extra
 * tap loses ~10% of users.
 *
 * **Why templates are parameters, not resource lookups.**
 * The production code in this project deliberately avoids
 * `testOptions.unitTests.includeAndroidResources = true` (it
 * breaks 270+ other Robolectric tests, see
 * `RecoveryPhraseHoldToRevealTest`'s class docstring for the
 * decision rationale). So this helper takes the formatted
 * strings as parameters and the Settings sheet — which has
 * access to the [androidx.compose.ui.res.stringResource]
 * composable — does the resource lookup and passes the
 * resolved string. The pure-function shape (Context +
 * AppVersion + 2 strings + optional crash log → Intent) is
 * trivially testable on the JVM without Android resources.
 *
 * **Privacy.** The body is built from the same template the
 * existing "Support" row uses (version + device + Android),
 * plus the contents of the most recent crash log file in
 * `cacheDir/crashes/`. The crash log is generated by
 * [CrashLog.write] and contains a `key=value` header
 * (timestamp, app version, device manufacturer/model, Android
 * SDK + release) and the unhandled exception's stack trace.
 * No third-party data, no analytics.
 */
object ReportProblemIntent {

    /**
     * Build the [Intent] the Settings sheet launches when the
     * user taps the "Report a problem" row. Pure function:
     * reads the most recent crash log from
     * [CrashLog.mostRecent] and assembles the body; the caller
     * is responsible for `startActivity(...)`.
     *
     * @param context the activity context (used for the crash
     *   log file lookup). The function does not retain a
     *   reference.
     * @param appVersion the running app's [AppVersion] (name +
     *   code) used in the subject and body.
     * @param subjectTemplate the localised subject template
     *   with `%1$s` for the app version name
     *   (`R.string.settings_report_problem_subject`).
     * @param bodyTemplate the localised body template. Use the
     *   one of:
     *   - `R.string.settings_report_problem_body_no_crash`
     *     (no crash log section)
     *   - `R.string.settings_report_problem_body_with_crash`
     *     (with `%5$s` for the crash log body)
     *   The caller picks the right one based on whether
     *   [CrashLog.mostRecent] returned non-null. The
     *   corresponding `getString(...)` invocation should
     *   already have been done by the caller (Compose
     *   `stringResource`); the helper formats the placeholders
     *   with `String.format` so the same `Context` can be
     *   used.
     * @param supportEmail the address to mailto:. Defaults to
     *   `R.string.settings_support_email`
     *   (`kaavalan-note@protonmail.com`) but is parameterised
     *   for testability and for a future build-flag override
     *   (e.g. a "department pilot" build that routes to an
     *   internal helpdesk).
     * @return the [Intent] (ACTION_SENDTO with mailto: URI).
     */
    fun build(
        context: Context,
        appVersion: AppVersion,
        subjectTemplate: String,
        bodyTemplate: String,
        supportEmail: String,
    ): Intent {
        val mostRecentCrash = CrashLog.mostRecent(context)
        val crashLogBody = mostRecentCrash?.readText()

        val formattedBody = String.format(
            bodyTemplate,
            appVersion.name,
            appVersion.code,
            Build.MANUFACTURER + " " + Build.MODEL,
            "Android " + Build.VERSION.RELEASE,
            // Pass an empty string for the crash-log slot
            // when no log exists. Extra `%n$s` arguments
            // are ignored by [String.format] if the
            // template doesn't reference them, so the
            // same 5-arg call works for both the no-crash
            // (4-placeholder) and with-crash
            // (5-placeholder) templates.
            crashLogBody.orEmpty(),
        )

        val subject = String.format(subjectTemplate, appVersion.name)

        val mailto = "mailto:" + supportEmail +
            "?subject=" + URLEncoder.encode(subject, "UTF-8") +
            "&body=" + URLEncoder.encode(formattedBody, "UTF-8")

        return Intent(Intent.ACTION_SENDTO).apply {
            data = Uri.parse(mailto)
        }
    }
}
